# Generated by Django 4.2.7 on 2024-01-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolstore',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='schoolstore',
            name='courses',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolstore',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='schoolstore',
            name='materials',
            field=models.ManyToManyField(to='school.material'),
        ),
        migrations.AlterField(
            model_name='schoolstore',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolstore',
            name='purpose',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Purpose',
        ),
    ]
